
export const portfolio = [
  {
    id: "1",
    title: "MUCOMA",
    description: "A cinematic masterpiece for client A.",
    category: "Sound Design & Mixing",
    imageUrl: "/img.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ownerProducer: "Mutiganda wa Nkunda",
  },
  {
    id: "2",
    title: "UMUGANI",
    description: "Award-winning documentary for client B.",
    category: "Sound Design & Mixing",
    imageUrl: "/img.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ownerProducer: "Kwezi John",
  },
   {
    id: "3",
    title: "SEAMS",
    description: "Award-winning documentary for client B.",
    category: "Sound Design & Mixing",
    imageUrl: "/img.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ownerProducer: "Rwasibo Nshuti & Ingabire Marie Louise",
  },
   {
    id: "4",
    title: "GIFT FROM CHILDHOOD",
    description: "Award-winning documentary for client B.",
    category: "Sound Design & Mixing",
    imageUrl: "/img.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ownerProducer: "Inkindi Jonathan",
  },
   {
    id: "5",
    title: "SILENCE BETWEEN US",
    description: "Award-winning documentary for client B.",
    category: "Sound Design & Mixing",
    imageUrl: "/img.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ownerProducer: "Delice",
  },
   {
    id: "6",
    title: "SEED OF CHANGE",
    description: "Award-winning documentary for client B.",
    category: "Sound Design & Mixing",
    imageUrl: "/img.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ownerProducer: "Shimwa Cedric",
  }
];
